apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: twenty-production

resources:
- ../base

replicas:
- name: twenty-server
  count: 1
- name: twenty-worker
  count: 1

configMapGenerator:
- name: twenty-config
  behavior: merge
  literals:
  - server-url=https://crm.4ow4.com
  - frontend-url=https://crm.4ow4.com
  - storage-bucket=twenty-storage-production
  - log-level=info
  - is-billing-enabled=true

patches:
- path: patches/server-resources.yaml
- path: patches/worker-resources.yaml
- path: patches/ingress.yaml
- path: patches/ssl-cert.yaml

images:
- name: twenty-app
  newName: us-central1-docker.pkg.dev/propods-crm/twenty-crm/twenty
  newTag: latest