# Production Secrets Template
# These values will be provided via GitHub Secrets in CI/CD
# This file is for reference only - actual secrets are created via kubectl

apiVersion: v1
kind: Secret
metadata:
  name: twenty-secrets
  namespace: twenty-production
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  pg-host: <base64-encoded-production-db-host>
  pg-user: <base64-encoded-production-db-user>
  pg-password: <base64-encoded-production-db-password>
  redis-url: <base64-encoded-production-redis-url>
  app-secret: <base64-encoded-production-app-secret>
  
  # Email SMTP credentials (required for production)
  smtp-user: <base64-encoded-smtp-user>
  smtp-password: <base64-encoded-smtp-password>
  
  # OAuth credentials (recommended for production)
  google-client-id: <base64-encoded-google-client-id>
  google-client-secret: <base64-encoded-google-client-secret>
  microsoft-client-id: <base64-encoded-microsoft-client-id>
  microsoft-client-secret: <base64-encoded-microsoft-client-secret>
  
  # Monitoring (required for production)
  sentry-dsn: <base64-encoded-sentry-dsn>
  sentry-front-dsn: <base64-encoded-sentry-front-dsn>

---
# Example of how to create secrets manually:
# kubectl create secret generic twenty-secrets \
#   --from-literal=pg-host="your-production-db-host" \
#   --from-literal=pg-user="twenty-user" \
#   --from-literal=pg-password="your-production-password" \
#   --from-literal=redis-url="redis://your-production-redis:6379" \
#   --from-literal=app-secret="your-production-app-secret" \
#   --from-literal=smtp-user="your-smtp-user" \
#   --from-literal=smtp-password="your-smtp-password" \
#   --namespace=twenty-production