apiVersion: v1
kind: ConfigMap
metadata:
  name: twenty-config
  labels:
    app: twenty
data:
  server-url: "https://propods.com"
  frontend-url: "https://propods.com"
  storage-bucket: "twenty-storage-ENVIRONMENT"
  log-level: "info"
  # Email configuration
  email-from-address: "noreply@propods.com"
  email-from-name: "Twenty CRM"
  email-system-address: "system@propods.com"
  # Feature flags
  is-billing-enabled: "false"
  is-multiworkspace-enabled: "true"
  is-email-verification-required: "true"
  # Security
  api-rate-limiting-ttl: "60"
  api-rate-limiting-limit: "100"
  mutation-maximum-affected-records: "100"