apiVersion: v1
kind: Service
metadata:
  name: twenty-server
  labels:
    app: twenty
    component: server
spec:
  type: ClusterIP
  selector:
    app: twenty
    component: server
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: twenty-sa
  labels:
    app: twenty
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twenty-storage-pvc
  labels:
    app: twenty
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 10Gi